In [2]:
import pandas as pd
import numpy as np

In [3]:
d1960 = pd.read_csv("60.csv", header=None, sep=";")
display(d1960.head(10000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"6 Chorale Preludes ""Schübler-Chorales"": Wachet...",Johann Sebastian Bach,spotify:track:4dZxCn07QoBsJwDBcjVGx1,"0,136","0,0334",3,"-27,654",1,"0,034","0,763","0,346","0,117","0,128","71,917",276627,4,"26,9243",14,0,3
2,"Carmen: Act I - ""Draussen am Wall von Sevilla""",Leipzig Radio Symphony Orchestra,spotify:track:6ReBerQMMWhvOBRkCXkpqv,"0,404","0,0634",2,"-20,219",1,"0,0998","0,966",0,"0,14","0,17","179,558",241467,3,"39,78497",11,0,3
3,"Carmen: Act I - ""Hier die Order!""",Leipzig Radio Symphony Orchestra,spotify:track:3SeLUsVmAGa1IBU7ozY5Bv,"0,412","0,148",1,"-19,607",1,"0,0609","0,965","7,87E-05","0,0619","0,308","101,028",121640,3,"42,65136",5,0,3
4,"Carmen: Act II - ""Sag. wen erwartest du?""",Leipzig Radio Symphony Orchestra,spotify:track:77Y4ScGGjVjC58LOaDh87Y,"0,403","0,0248",9,"-27,787",1,"0,14","0,959",0,"0,211","0,218","171,132",75107,3,"31,62991",3,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,You're My World,Cilla Black,spotify:track:2hWfpElGMOzQavDEgVbtLz,"0,388","0,368",1,"-8,375",1,"0,0269","0,808","0,0083","0,0449","0,466","95,735",179467,3,"26,82369",7,1,3
997,You've Made Me So Very Happy,Brenda Holloway,spotify:track:4lHkuSUGjwstBAJoimtjnk,"0,511","0,434",7,"-11,185",1,"0,028","0,212",0,"0,154","0,778","98,645",173227,4,"72,05739",8,1,3
998,Yuri Approaches Lara's Apartment,Maurice Jarre,spotify:track:5KxikpGsUL8l1Sk63NcILW,"0,162","0,0383",2,"-29,914",1,"0,0375","0,242","0,354","0,205","0,0766","130,875",49533,4,"5,69742",3,0,3
999,Zelda's Theme,Pérez Prado,spotify:track:7cSm6RF5oP4rw3d40pfY5b,"0,849","0,898",7,"-6,064",1,"0,0388","0,734","0,865","0,0438","0,967","134,396",120987,4,"44,15837",5,0,3
1000,Zero Hour,David Lindup,spotify:track:3YC91rbHjh9MgpMMoh6Xog,"0,431","0,454",7,"-14,31",1,"0,0302","0,524","0,13","0,116","0,585","129,589",83360,4,"35,03921",5,0,3

In [4]:
d1970 = pd.read_csv("70.csv", header=None, sep=";")
display(d1970.head(10000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"Der Berg (Aus "" Der Watzmann ruft "" ) - Live",Wolfgang Ambros,spotify:track:18CACQBgOwkGXMlUl7xBOk,"0,346","0,284",9,"-19,699",0,"0,236","0,64","0,0001","0,985","0,27","133,362",299267,4,"49,66483",11,0,4
2,"Evergreen (Love Theme From ""A Star Is Born"")",Barbra Streisand,spotify:track:2IcqY68BxP1ONPi3ME6aje,"0,335","0,303",9,"-10,943",1,"0,0315","0,932","0,0271","0,0907","0,186","114,224",184800,4,"16,95608",12,1,4
3,Intrusion des racketteurs noirs dans les maiso...,François de Roubaix,spotify:track:4tmvVO8Im8i4PYjZHYzS5E,"0,526","0,313",7,"-20,736",0,"0,0572","0,606","0,832","0,101","0,371","99,624",356347,4,"21,08757",14,0,4
4,"The Ballad of Sweeney Todd: ""Sweeney Pondered ...",Stephen Sondheim,spotify:track:2vaIZdW4YI9EJn8dFrB955,"0,546","0,62",8,"-11,298",1,"0,104","0,972","8,41E-06","0,409","0,366","132,445",31107,4,"7,69751",3,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Young Hearts Run Free,Candi Staton,spotify:track:3MFa9idQuY4iJLWsZl3tIQ,"0,653","0,652",7,"-9,304",0,"0,0427","0,13","1,58E-05","0,202","0,846","115,388",248360,4,"23,77595",15,1,4
997,Your Love Is Like A Cancer,Son Seals,spotify:track:6zl81YN27QExitw4AZUDy1,"0,699","0,652",9,"-10,831",0,"0,0397","0,21","1,70E-05","0,0578","0,969","147,786",276000,4,"40,64539",12,0,4
998,Your Own Special Way,Genesis,spotify:track:2yOJ8rGhSns3kCr9WJHDgj,"0,319","0,196",5,"-11,466",1,"0,0333","0,686","3,19E-06","0,112","0,0636","130,557",378813,3,"131,80721",12,1,4
999,Your Time To Cry,Joe Simon,spotify:track:3f3peHdm971oH29Tul50tK,"0,572","0,437",9,"-10,488",0,"0,0406","0,772","1,19E-05","0,331","0,576","115,914",179733,3,"52,33987",9,1,4
1000,Yo-Yo,The Osmonds,spotify:track:1FWHRqOV17plc9w1SSVPo4,"0,617","0,785",2,"-5,8",1,"0,0565","0,636",0,"0,174","0,92","138,057",195787,4,"29,23776",12,1,4

In [5]:
d1980 = pd.read_csv("80.csv", header=None, sep=";")
display(d1980.head(10000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"Overture (The Big Race) - From ""Pee Wee's Big ...",Danny Elfman,spotify:track:1P9PYvV5kuZ9dAACp3qSQm,"0,297","0,219",1,"-14,216",1,"0,0335","0,959","0,765","0,108","0,0483","133,757",188267,3,"16,80054",10,0,5
2,"Rapper's Delight - 7"" Single Version",The Sugarhill Gang,spotify:track:1FnxNtKli7rcB9IU4J8MEg,"0,905","0,692",2,"-14,143",1,"0,199","0,22",0,"0,128","0,943","111,292",305413,4,"35,37898",15,0,5
3,"Surrender To Me (From ""Tequila Sunrise"")",Ann Wilson & Robin Zander,spotify:track:0Mqlf5OTGoeUgoeqL1Mzew,"0,37","0,683",11,"-5,702",0,"0,036","0,452","8,11E-06","0,167","0,118","148,052",244733,4,"40,02333",15,1,5
4,"Symphonie ""Mathis der Maler"": 1. Engelkonzert",Paul Hindemith,spotify:track:4QK6arNqmckObVn9K6Dy28,"0,254","0,0807",2,"-21,713",1,"0,0428","0,906","0,918","0,36","0,0471","112,522",504627,4,"50,94702",22,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,הפרח בגני,Zohar Argov,spotify:track:65SBc367d0Wra0HTW9eNqj,"0,275","0,49",0,"-16,252",0,"0,0364","0,227","9,09E-06","0,0685","0,734","174,184",222133,4,"31,26596",8,0,5
997,להלה יזיד אקטר,Zohar Argov,spotify:track:6hiUDxFtitzC1K2GgjxnRI,"0,456","0,558",9,"-12,763",0,"0,0877","0,45","9,02E-05","0,175","0,389","109,509",338627,4,"33,24057",14,0,5
998,לשיר איתך,Boaz Sharabi,spotify:track:0rlIsdv5bdnAdhC69rpXAn,"0,477","0,429",0,"-10,286",1,"0,0328","0,714",0,"0,0437","0,208","76,591",267440,4,"53,74987",13,0,5
999,נשבע,Haim Moshe,spotify:track:7bxlXnh1YMHQZHQm04oNrk,"0,406","0,24",11,"-14,13",0,"0,032","0,861","2,58E-06","0,11","0,136","83,168",254333,4,"48,15516",11,0,5
1000,עוד דקה את נעלמת,Zohar Argov,spotify:track:2bTXTDIF3KTrhGyvO8OTXG,"0,448","0,34",7,"-14,618",0,"0,0283","0,321","0,000374","0,105","0,299","98,406",245600,4,"28,99532",13,0,5

In [6]:
d1990 = pd.read_csv("90.csv", header=None, sep=";")
display(d1990.head(10000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"Don't Cry For Me Argentina (From ""Evita"")",Madonna,spotify:track:0XzS20zTg74EyoM1dDORlE,"0,297","0,148",11,"-13,898",1,"0,0337","0,897","4,03E-06","0,099","0,082","104,458",335733,5,"44,7754",17,1,6
2,"I Love Music (From ""Carlito's Way"")",Rozalla,spotify:track:7bf3WkBlgMvE2n0F96LQja,"0,714","0,686",2,"-8,428",0,"0,0294","0,0376","0,0043","0,0853","0,842","125,982",290000,4,"26,85643",13,1,6
3,"Let It Go (From ""Set It Off"")",Ray J,spotify:track:6igXETl1zKir06CA7NWYo2,"0,853","0,515",0,"-5,081",1,"0,0453","0,0547","7,79E-05","0,0519","0,859","93,026",293129,4,"32,89598",11,1,6
4,"Oscar's ""B"" Sandwich",Oscar the Grouch,spotify:track:32WQuOyYBxZW1Q8tmL7amK,"0,778","0,573",0,"-9,285",1,"0,355","0,795",0,"0,753","0,966","107,087",64773,3,"11,3163",3,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,แพ้ใจ,Mai Charoenpura,spotify:track:6Z5nlPYAN6WfubM40ELc6X,"0,672","0,398",0,"-8,758",1,"0,0281","0,57",0,"0,16","0,314","74,007",221387,4,"38,42628",10,0,6
997,ขอจันทร์,Viyada Komarakul Na Nakorn,spotify:track:0U0w3Ih5zX45OJCW12xlaj,"0,689","0,366",9,"-11,952",1,"0,0287","0,838","0,000135","0,056","0,371","129,805",240267,4,"71,54559",10,0,6
998,คงเดิม,Asanee & Wasan,spotify:track:6yVQGme4IdVTzznp9MmeON,"0,707","0,603",7,"-9,533",1,"0,0267","0,477","1,23E-06","0,098","0,756","119,995",222360,4,"44,53343",12,0,6
999,วิมานดิน,Nantida Kaewbuasai,spotify:track:05Hdc4jTJq9yyl89kXGCvy,"0,646","0,389",3,"-7,438",1,"0,0252","0,866",0,"0,187","0,242","131,986",251813,4,"47,49447",10,0,6
1000,หยุดเลย,J Jetrin,spotify:track:34ymFuVHX4eH1q3uXTh4pQ,"0,586","0,546",9,"-8,547",0,"0,0265","0,454",0,"0,0935","0,262","140,824",250387,4,"41,72215",11,0,6

In [7]:
d2000 = pd.read_csv("2000.csv", header=None, sep=";")
display(d2000.head(10000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"Collage #1 (""Blue Suede"")",James Tenney,spotify:track:70klYxQLBSSonN3KrbNU0l,"0,31","0,707",11,"-12,054",1,"0,509","0,912","0,0562","0,108","0,37","56,028",206067,4,"17,18683",9,0,1
2,"Deus Passus. ""St. Luke Passion"": Das ist mein ...",Wolfgang Rihm,spotify:track:2O7HKUweyR9yP9pOSdAD1p,"0,194","0,00511",0,"-43,178",0,"0,047","0,945","0,00193","0,0769","0,0321","84,79",188000,4,"48,25093",12,0,1
3,"I Won't Say (I'm In Love) - From ""Hercules"" / ...",Susan Egan,spotify:track:3Dupb5AcaVFErlSSfl3szW,"0,684","0,471",0,"-9,43",1,"0,043","0,208",0,"0,14","0,453","121,081",140093,4,"28,03726",8,0,1
4,Look On The Bright Side Of Life (All Things Du...,Monty Python,spotify:track:4yEoBe0b9paEGQrUIGxBCb,"0,691","0,528",7,"-9,333",1,"0,194","0,624","0,00226","0,127","0,693","120,776",238293,4,"42,37658",9,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,You're Beautiful,James Blunt,spotify:track:7j6C8ITuzhA7GHmj2z9mSd,"0,66","0,183",3,"-15,238",1,"0,068","0,994","0,928","0,119","0,218","78,936",177066,4,"28,33464",10,1,1
997,You're Gonna Go Far. Kid,The Offspring,spotify:track:6TfBA04WJ3X1d1wXhaCFVT,"0,55","0,917",0,"-3,159",1,"0,0638","0,00428",0,"0,197","0,601","126,115",177827,4,"35,7375",9,1,1
998,You're My Better Half,Keith Urban,spotify:track:06ySRvEnrUxZZ9ml3VO2TY,"0,655","0,747",4,"-4,41",1,"0,0333","0,0369","1,29E-06","0,0449","0,613","118,054",239400,4,"23,15763",12,1,1
999,Zombie Jamboree (Back To Back),Harry Belafonte,spotify:track:1WC367oL0q70xpMlGuy90b,"0,718","0,708",7,"-8,523",1,"0,15","0,54",0,"0,27","0,95","87,24",199200,4,"27,06017",9,0,1
1000,คนไร้ค่า,Stone Metal Fire,spotify:track:0K1U7QPsuA6tU0gJTvHZpC,"0,473","0,464",10,"-8,112",0,"0,0287","0,00267","0,000663","0,107","0,25","128,955",272400,3,"47,53233",12,0,1

In [8]:
d2010 = pd.read_csv("2010.csv", header=None, sep=";")
display(d2010.head(10000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"Game Of Thrones - From The ""Game Of Thrones"" S...",Ramin Djawadi,spotify:track:2kgJYQKyQ1CK5GWcCUGwwh,"0,551","0,558",8,"-18,029",1,"0,0431","0,483","0,675","0,102","0,168","146,039",78293,3,"30,4268",5,0,2
2,"Glass: Truman Sleeps (From ""The Truman Show"")",Philip Glass,spotify:track:2fwzsUkquSIHQbBjrayijJ,"0,416","0,0937",5,"-18,928",0,"0,0336","0,951","0,948","0,106","0,0967","134,468",99533,4,"69,7431",3,0,2
3,"Holes In The Sky - From The ""Insurgent"" Soundt...",M83,spotify:track:0m6pHsgfp0w35w1mEOVepJ,"0,123","0,494",0,"-9,123",1,"0,0339","0,146","0,0164","0,109","0,0742","68,703",261307,4,"15,4475",10,0,2
4,"Milegi Milegi (From ""Stree"")",Mika Singh,spotify:track:52uiJsA4FrtAZlgqxCJwJI,"0,843","0,892",2,"-4,371",1,"0,0527","0,0512","1,13E-06","0,101","0,655","125,991",153745,4,"30,41224",9,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Your Disposal,Cattle Decapitation,spotify:track:3FGzV0BJ4TqcKwBSOjH6xs,"0,323","0,985",4,"-4,413",1,"0,205","2,42E-05","0,592","0,575","0,151","114,778",287307,4,"52,85167",10,0,2
997,Yours,Russell Dickerson,spotify:track:6RSNKGdv3nDTHqgw4bdzyF,"0,555","0,722",11,"-6,005",1,"0,034","0,119",0,"0,0861","0,559","134,058",216960,4,"47,84163",8,1,2
998,Zombie,Chief State,spotify:track:2ldgaCumYp2YqeVqCpKA4h,"0,473","0,967",5,"-4,86",0,"0,0792","0,000111","0,00259","0,101","0,453","188,001",208423,4,"56,98689",10,0,2
999,我がままなハイヒール - Non Stop Mix ver.,秋元薫,spotify:track:7rwK52xzfFuyCv8VD1p9tL,"0,816","0,715",7,"-7,068",1,"0,0419","0,297","0,00605","0,124","0,823","105,62",166571,4,"31,25894",9,0,2
1000,胜者为王,窒息,spotify:track:3SvDPc19Cm6O3EfHBJFylH,"0,516","0,958",9,"-3,439",0,"0,128","0,00672","0,0342","0,0679","0,484","104,717",232520,4,"41,39266",12,0,2

In [9]:
df_decadas=pd.concat([d1960,d1970,d1980,d1990,d2000,d2010])
display(df_decadas.head(60000))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,dataset_of_track,dataset_of_artist,dataset_of_uri,dataset_of_danceability,dataset_of_energy,dataset_of_key,dataset_of_loudness,dataset_of_mode,dataset_of_speechiness,dataset_of_acousticness,dataset_of_instrumentalness,dataset_of_liveness,dataset_of_valence,dataset_of_tempo,dataset_of_duration_ms,dataset_of_time_signature,dataset_of_chorus_hit,dataset_of_sections,dataset_of_target,dataset_of_id_ano
1,"6 Chorale Preludes ""Schübler-Chorales"": Wachet...",Johann Sebastian Bach,spotify:track:4dZxCn07QoBsJwDBcjVGx1,"0,136","0,0334",3,"-27,654",1,"0,034","0,763","0,346","0,117","0,128","71,917",276627,4,"26,9243",14,0,3
2,"Carmen: Act I - ""Draussen am Wall von Sevilla""",Leipzig Radio Symphony Orchestra,spotify:track:6ReBerQMMWhvOBRkCXkpqv,"0,404","0,0634",2,"-20,219",1,"0,0998","0,966",0,"0,14","0,17","179,558",241467,3,"39,78497",11,0,3
3,"Carmen: Act I - ""Hier die Order!""",Leipzig Radio Symphony Orchestra,spotify:track:3SeLUsVmAGa1IBU7ozY5Bv,"0,412","0,148",1,"-19,607",1,"0,0609","0,965","7,87E-05","0,0619","0,308","101,028",121640,3,"42,65136",5,0,3
4,"Carmen: Act II - ""Sag. wen erwartest du?""",Leipzig Radio Symphony Orchestra,spotify:track:77Y4ScGGjVjC58LOaDh87Y,"0,403","0,0248",9,"-27,787",1,"0,14","0,959",0,"0,211","0,218","171,132",75107,3,"31,62991",3,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Your Disposal,Cattle Decapitation,spotify:track:3FGzV0BJ4TqcKwBSOjH6xs,"0,323","0,985",4,"-4,413",1,"0,205","2,42E-05","0,592","0,575","0,151","114,778",287307,4,"52,85167",10,0,2
997,Yours,Russell Dickerson,spotify:track:6RSNKGdv3nDTHqgw4bdzyF,"0,555","0,722",11,"-6,005",1,"0,034","0,119",0,"0,0861","0,559","134,058",216960,4,"47,84163",8,1,2
998,Zombie,Chief State,spotify:track:2ldgaCumYp2YqeVqCpKA4h,"0,473","0,967",5,"-4,86",0,"0,0792","0,000111","0,00259","0,101","0,453","188,001",208423,4,"56,98689",10,0,2
999,我がままなハイヒール - Non Stop Mix ver.,秋元薫,spotify:track:7rwK52xzfFuyCv8VD1p9tL,"0,816","0,715",7,"-7,068",1,"0,0419","0,297","0,00605","0,124","0,823","105,62",166571,4,"31,25894",9,0,2
1000,胜者为王,窒息,spotify:track:3SvDPc19Cm6O3EfHBJFylH,"0,516","0,958",9,"-3,439",0,"0,128","0,00672","0,0342","0,0679","0,484","104,717",232520,4,"41,39266",12,0,2

In [10]:
df_decadas.to_csv("saida_6decadas_colab.csv", index=False, sep=";", encoding="utf-8-sig")